name: Practica CI

on: push

jobs:
  job_build:
    runs-on: ubuntu-latest

    steps:
      
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check Node.js version
        run: node --version
      
      - name: instalar dependencias
        run: npm install
      
      - name: ejecutar pruebas
        run: npm test
      
      - name: build
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  job_deploy:
    runs-on: ubuntu-latest
    needs: job_build
    permissions:
      pages: write    
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: deploy
        run: echo "Desplegando la aplicacion"

      - name: Deploy
        id: deployment-pages
        uses: actions/deploy-pages@v4 
      
      - name: Obtener URL de la página
        run: echo " ${{ steps.deployment-pages.outputs.deployment-url }}"

  job_notificacion:
    runs-on: ubuntu-latest
    if: ${{ always()}}
    needs: job_deploy
      
    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: Send Email via Gmail
        uses: Raghul-M/gmail-sender-action@v1
        with:
          sender_email: ${{ secrets.GMAIL_SENDER }}
          app_password: ${{ secrets.GMAIL_APP_PASSWORD }}
          receiver_emails: ${{ secrets.RECIPIENTS }}
          template_path: "templates/email_template.html"
          subject: "Notification from GitHub Action de Daniela H"
