name: Practica CI

on: push

jobs:
  job_build:
    runs-on: ubuntu-latest

    steps:
      
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check Node.js version
        run: node --version
      
      - name: instalar dependencias
        run: npm install
      
      - name: ejecutar pruebas
        run: npm test


  job_deploy:
    runs-on: ubuntu-latest
    needs: job_configuraciones

    steps:

      - name: deploy
        run: echo "Desplegando la aplicacion"