name: practica secretros y variables de entorno

on: push

jobs: 
  job_variables:
    runs-on: ubuntu-latest

    steps:
      - name: print variable
        run: echo "La variable de entorno es: ${{ secrets.EJEMPLO_VARIBLE_ENTORNO }}"
    
    job_secretos:
      runs-on: ubuntu-latest

      steps:
        - name: print secreto
          run: echo "El secreto es: ${{ secrets.PRUEBA_SECRETO }}"
          

